python test_mlm_w_mask.py -lang en -mname xlm-roberta-base
python test_mlm_w_mask.py -lang zh -mname xlm-roberta-base
python test_mlm_w_mask.py -lang fa -mname xlm-roberta-base
python test_mlm_w_mask.py -lang hi -mname xlm-roberta-base
python test_mlm_w_mask.py -lang sw -mname xlm-roberta-base
python test_mlm_w_mask.py -lang en -mname xlm-roberta-large
python test_mlm_w_mask.py -lang zh -mname xlm-roberta-large
python test_mlm_w_mask.py -lang fa -mname xlm-roberta-large
python test_mlm_w_mask.py -lang hi -mname xlm-roberta-large
python test_mlm_w_mask.py -lang sw -mname xlm-roberta-large
python test_mlm_w_mask.py -lang en -mname google/mt5-small
python test_mlm_w_mask.py -lang zh -mname google/mt5-small
python test_mlm_w_mask.py -lang fa -mname google/mt5-small
python test_mlm_w_mask.py -lang hi -mname google/mt5-small
python test_mlm_w_mask.py -lang sw -mname google/mt5-small
python test_mlm_w_mask.py -lang en -mname google/mt5-base
python test_mlm_w_mask.py -lang zh -mname google/mt5-base
python test_mlm_w_mask.py -lang fa -mname google/mt5-base
python test_mlm_w_mask.py -lang hi -mname google/mt5-base
python test_mlm_w_mask.py -lang sw -mname google/mt5-base
python test_mlm_w_mask.py -lang en -mname google/mt5-large
python test_mlm_w_mask.py -lang zh -mname google/mt5-large
python test_mlm_w_mask.py -lang fa -mname google/mt5-large
python test_mlm_w_mask.py -lang hi -mname google/mt5-large
python test_mlm_w_mask.py -lang sw -mname google/mt5-large
python test_mlm_w_mask.py -lang en -mname facebook/xglm-564M
python test_mlm_w_mask.py -lang zh -mname facebook/xglm-564M
python test_mlm_w_mask.py -lang fa -mname facebook/xglm-564M
python test_mlm_w_mask.py -lang hi -mname facebook/xglm-564M
python test_mlm_w_mask.py -lang sw -mname facebook/xglm-564M
python test_mlm_w_mask.py -lang en -mname facebook/xglm-1.7B
python test_mlm_w_mask.py -lang zh -mname facebook/xglm-1.7B
python test_mlm_w_mask.py -lang fa -mname facebook/xglm-1.7B
python test_mlm_w_mask.py -lang hi -mname facebook/xglm-1.7B
python test_mlm_w_mask.py -lang sw -mname facebook/xglm-1.7B
python test_mlm_w_mask.py -lang en -mname facebook/xglm-2.9B
python test_mlm_w_mask.py -lang zh -mname facebook/xglm-2.9B
python test_mlm_w_mask.py -lang fa -mname facebook/xglm-2.9B
python test_mlm_w_mask.py -lang hi -mname facebook/xglm-2.9B
python test_mlm_w_mask.py -lang sw -mname facebook/xglm-2.9B
python test_mlm_w_mask.py -lang en -mname facebook/xglm-4.5B
python test_mlm_w_mask.py -lang zh -mname facebook/xglm-4.5B
python test_mlm_w_mask.py -lang fa -mname facebook/xglm-4.5B
python test_mlm_w_mask.py -lang hi -mname facebook/xglm-4.5B
python test_mlm_w_mask.py -lang sw -mname facebook/xglm-4.5B

